### ISSUE TITLE
linux suport 

### ISSUE THREAD

**Issue by MimzyFang** [amongservers/launcher#1]
imposter has a cli server injector native on Linux and [among us editor](https://github.com/Koupah/Among-Us-Editor) has a gui to change server so why not implement is in this launcher to

**Comment by alandoherty** [comment]
The problem with running the launcher on Linux is we use WPF. You could technically run the launcher potentially with Mono/Wine, since I think they support WPF. We decided to use WPF because the Among Us game works best on Windows.

The reason Among Us Editor works on Linux is because it uses Java, which is easily cross-platform.

**Comment by MimzyFang** [comment]
it runs with wine but it obviously cant find the folder
